### PR TITLE
Increase speed deserialize

### PR DESCRIPTION
**Pull request by mvsavkin**
My changes increase speed deserialize approximately twice.

I changed structure black and white list since it contain mainly full-package name.

And my PR contains changes from another open PR.

Best regards

### CODE REVIEW

**Comment by mvsavkin** [comment]
And my PR contains changes from another open PR.

Best regards

**Comment by ikkisoft** [comment]
Reverting the following change in the next release - _TemplateList_ as implemented does not work:
https://github.com/ikkisoft/SerialKiller/pull/14/commits/0453ebe64a7fab1f67587172cddc2d71748f88be

I've kept the speed test since it's a useful benchmark.

**Comment by mvsavkin** [comment]
What specifically does not work?
Will you have kept an approach with HashSet?

**Comment by ikkisoft** [comment]
Sorry for the late reply.

``if (config.blacklist.getNames().contains(serialInput.getName())){`` cannot work because the config does not just contain fully qualified Class names

**Comment by mvsavkin** [comment]
You are not right. 
Above this code is a loop that checks the patterns.

For improve speed deserialize blacklists and whitelists additionally were divide on lists full name(i.e. most class is fully qualified Class names) and patterns regexps(old functional). At first was checked regexps and after was checked fully qualified Class Names.

Please check code again and will do revert again.
If something was wrong please tell me and I will correct.

Best regards,
Maksim

**Pull request merged**
